#!/usr/bin/env python3
"""
IServ to Notion Sync
====================
Syncs emails from an IServ school platform to a Notion database.
Runs as a daily GitHub Actions cron job.

Author: Generated by Sol (Notion AI)
License: MIT
"""

import os
import sys
import json
import time
import logging
import importlib.util
from datetime import datetime
from typing import Dict, List, Any, Optional

import requests
from bs4 import BeautifulSoup

# ---------------------------------------------------------------------------
# IServAPI bug workaround (v1.4.0)
# ---------------------------------------------------------------------------
_spec = importlib.util.find_spec("IServAPI")
if _spec and _spec.origin:
    with open(_spec.origin, "r") as _f:
        _content = _f.read()
    if "from turtle import st" in _content:
        _content = _content.replace(
            "from turtle import st",
            "from typing import Any, Literal",
        )
        _content = _content.replace(
            "\nclass IServAPI:",
            "\nAlarmType = Any\nRecurring = dict\n\nclass IServAPI:",
        )
        with open(_spec.origin, "w") as _f:
            _f.write(_content)
        logging.info("Patched IServAPI bug")

from IServAPI import IServAPI

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

ISERV_USERNAME = os.environ.get("ISERV_USERNAME")
ISERV_PASSWORD = os.environ.get("ISERV_PASSWORD")
ISERV_URL = os.environ.get("ISERV_URL")
NOTION_TOKEN = os.environ.get("NOTION_TOKEN")
NOTION_DATABASE_ID = os.environ.get("NOTION_DATABASE_ID")

NOTION_API_URL = "https://api.notion.com/v1"
NOTION_VERSION = "2022-06-28"
MAX_EMAILS = 50
RATE_LIMIT_SEC = 0.35

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


def validate_config() -> None:
    required = ["ISERV_USERNAME", "ISERV_PASSWORD", "ISERV_URL", "NOTION_TOKEN", "NOTION_DATABASE_ID"]
    missing = [v for v in required if not os.environ.get(v)]
    if missing:
        logger.error(f"Missing environment variables: {', '.join(missing)}")
        sys.exit(1)


def fetch_iserv_emails() -> List[Dict[str, Any]]:
    """Login to IServ, fetch emails via raw HTTP, return parsed email list."""
    print("=" * 60, flush=True)
    print("STEP 1: IServ Login", flush=True)
    print(f"  URL: {ISERV_URL}", flush=True)

    iserv = IServAPI(
        username=ISERV_USERNAME,
        password=ISERV_PASSWORD,
        iserv_url=ISERV_URL,
    )
    print("  Login: OK", flush=True)

    # Use the internal session (authenticated) to make a raw request
    session = iserv._session
    mail_url = f"{{https://{ISERV_URL}}}/iserv/mail/api/message/list?path=INBOX&length={MAX_EMAILS}&start=0&order%5Bcolumn%5D=date&order%5Bdir%5D=desc"

    print("=" * 60, flush=True)
    print("STEP 2: Fetching emails via raw HTTP", flush=True)
    print(f"  URL: {mail_url}", flush=True)

    resp = session.get(mail_url)
    print(f"  Status: {resp.status_code}", flush=True)
    print(f"  Content-Type: {resp.headers.get('Content-Type', 'unknown')}", flush=True)
    print(f"  Response length: {len(resp.text)} chars", flush=True)
    print(f"  First 500 chars:\n{resp.text[:500]}", flush=True)
    print("  ...", flush=True)
    print(f"  Last 500 chars:\n{resp.text[-500:]}", flush=True)

    # Write raw response to file for artifact upload
    with open("debug_raw_response.html", "w", encoding="utf-8") as f:
        f.write(resp.text)
    print("  Wrote raw response to debug_raw_response.html", flush=True)

    # Try 1: Parse as JSON directly
    data = None
    try:
        data = resp.json()
        print("  Parsed as JSON directly: OK", flush=True)
    except Exception:
        print("  JSON parse failed, trying HTML parse...", flush=True)

    # Try 2: Parse as HTML, extract <script id="php-data">
    if data is None:
        soup = BeautifulSoup(resp.text, "html.parser")
        script_tag = soup.find("script", id="php-data")
        if script_tag:
            print("  Found <script id='php-data'> tag", flush=True)
            raw_content = script_tag.string or ""
            print(f"  Script content length: {len(raw_content)} chars", flush=True)
            print(f"  Script first 1000 chars:\n{raw_content[:1000]}", flush=True)
            try:
                data = json.loads(raw_content.strip())
                print("  Parsed script JSON: OK", flush=True)
            except Exception as exc:
                print(f"  Script JSON parse failed: {exc}", flush=True)
                with open("debug_script_content.txt", "w", encoding="utf-8") as f:
                    f.write(raw_content)
                print("  Wrote script content to debug_script_content.txt", flush=True)
        else:
            print("  No <script id='php-data'> tag found!", flush=True)
            if "login" in resp.text.lower() or "password" in resp.text.lower():
                print("  WARNING: Response looks like a login page", flush=True)

    if data is None:
        print("  ERROR: Could not extract email data from response", flush=True)
        return []

    # Write parsed data to file
    with open("debug_parsed_data.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, default=str, indent=2)
    print("  Wrote parsed data to debug_parsed_data.json", flush=True)

    # Extract email list
    print("=" * 60, flush=True)
    print("STEP 3: Extracting email list", flush=True)
    print(f"  Data type: {type(data).__name__}", flush=True)

    if isinstance(data, dict):
        print(f"  Dict keys: {list(data.keys())}", flush=True)
        if "data" in data:
            emails = data["data"]
            print(f"  Found 'data' key, type: {type(emails).__name__}, length: {len(emails) if isinstance(emails, list) else 'N/A'}", flush=True)
        else:
            emails = [data]
            print("  No 'data' key, wrapping dict in list", flush=True)
    elif isinstance(data, list):
        emails = data
        print(f"  List length: {len(emails)}", flush=True)
    else:
        print(f"  Unexpected type: {type(data)}", flush=True)
        emails = []

    if emails and isinstance(emails[0], dict):
        print(f"  First email keys: {list(emails[0].keys())}", flush=True)
        print(f"  First email content:", flush=True)
        for k, v in emails[0].items():
            print(f"    {k}: {str(v)[:200]}", flush=True)
    elif emails:
        print(f"  First email type: {type(emails[0]).__name__}, value: {str(emails[0])[:200]}", flush=True)

    print(f"  Total emails: {len(emails)}", flush=True)
    return emails


def _first(row: Dict[str, Any], *keys: str) -> Optional[Any]:
    for k in keys:
        if k in row and row[k] is not None:
            return row[k]
    return None


def _strip_html(text: Any) -> str:
    if text is None:
        return ""
    s = str(text)
    import re
    s = re.sub(r'<[^>]+>', '', s)
    s = s.replace('&amp;', '&').replace('&lt;', '<').replace('&gt;', '>')
    s = s.replace('&quot;', '"').replace('&#39;', "'").replace('&nbsp;', ' ')
    return s.strip()


def parse_email(raw: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(raw, dict):
        return {"uid": None, "subject": "(Parse Error)", "sender": "Unbekannt", "date_iso": None, "is_read": False, "preview": ""}

    uid = _first(raw, "uid", "UID", "id", "ID", "message_id", "messageId", "DT_RowId", "rowId", "msg", "number")
    subject = _first(raw, "subject", "Subject", "betreff", "Betreff", "title", "Title", "name", "Name")
    sender = _first(raw, "from", "From", "from_name", "sender", "absender", "fromEmail", "from_email", "senderEmail")
    date_val = _first(raw, "date", "Date", "date_timestamp", "timestamp", "time", "Time", "dateReceived", "received")
    seen = _first(raw, "seen", "read", "is_read", "gelesen", "unread", "isRead", "wasRead", "flags", "flag")
    preview = _first(raw, "preview", "snippet", "excerpt", "vorschau", "text", "body", "content", "previewText")

    if subject is None:
        subject = _first(raw, "1", "2", "0")
    if sender is None:
        sender = _first(raw, "2", "3", "1")
    if date_val is None:
        date_val = _first(raw, "3", "4", "5")

    subject = _strip_html(subject) if subject else "(Kein Betreff)"
    sender = _strip_html(sender) if sender else "Unbekannt"
    preview = _strip_html(preview) if preview else ""
    if not subject:
        subject = "(Kein Betreff)"
    if not sender:
        sender = "Unbekannt"

    date_iso: Optional[str] = None
    if date_val is not None:
        if isinstance(date_val, (int, float)):
            date_iso = datetime.fromtimestamp(int(date_val)).isoformat()
        else:
            ds = _strip_html(date_val)
            for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S", "%d.%m.%Y %H:%M:%S", "%Y-%m-%d %H:%M", "%d.%m.%Y", "%Y-%m-%d"):
                try:
                    date_iso = datetime.strptime(ds, fmt).isoformat()
                    break
                except ValueError:
                    continue
            if date_iso is None:
                try:
                    date_iso = datetime.fromisoformat(ds).isoformat()
                except (ValueError, TypeError):
                    date_iso = datetime.now().isoformat()

    if isinstance(seen, bool):
        is_read = seen
    elif isinstance(seen, str):
        is_read = seen.lower() in ("true", "1", "yes", "gelesen", "read")
    elif isinstance(seen, (int, float)):
        is_read = bool(seen)
    else:
        is_read = False

    if preview and len(preview) > 200:
        preview = preview[:200] + "…"

    uid_str = str(uid).strip() if uid is not None else None
    return {"uid": uid_str, "subject": subject, "sender": sender, "date_iso": date_iso, "is_read": is_read, "preview": preview}


def notion_headers() -> Dict[str, str]:
    return {"Authorization": f"Bearer {NOTION_TOKEN}", "Notion-Version": NOTION_VERSION, "Content-Type": "application/json"}

def get_existing_uids() -> set:
    existing = set()
    cursor = None
    has_more = True
    while has_more:
        body = {"page_size": 100}
        if cursor:
            body["start_cursor"] = cursor
        resp = requests.post(f"{NOTION_API_URL}/databases/{NOTION_DATABASE_ID}/query", headers=notion_headers(), json=body)
        if resp.status_code != 200:
            logger.error(f"Notion query failed: {resp.status_code} — {resp.text[:300]}")
            break
        data = resp.json()
        for page in data.get("results", []):
            props = page.get("properties", {})
            uid_prop = props.get("IServ UID", {})
            rt = uid_prop.get("rich_text", [])
            if rt:
                existing.add(rt[0].get("plain_text", ""))
        has_more = data.get("has_more", False)
        cursor = data.get("next_cursor")
    logger.info(f"Found {len(existing)} existing emails in Notion")
    return existing

def create_notion_page(email: Dict[str, Any]) -> bool:
    properties = {
        "Betreff": {"title": [{"text": {"content": email["subject"][:2000]}}]},
        "Absender": {"rich_text": [{"text": {"content": email["sender"][:2000]}}]},
        "Gelesen": {"checkbox": email["is_read"]},
        "Vorschau": {"rich_text": [{"text": {"content": email["preview"][:2000]}}]},
        "Ordner": {"select": {"name": "Posteingang"}},
    }
    if email["date_iso"]:
        properties["Datum"] = {"date": {"start": email["date_iso"]}}
    if email["uid"]:
        properties["IServ UID"] = {"rich_text": [{"text": {"content": email["uid"]}}]}
    resp = requests.post(f"{NOTION_API_URL}/pages", headers=notion_headers(), json={"parent": {"database_id": NOTION_DATABASE_ID}, "properties": properties})
    if resp.status_code == 200:
        logger.info(f"  Created: {email['subject'][:60]}")
        return True
    else:
        logger.error(f"  Failed ({resp.status_code}): {resp.text[:200]}")
        return False


def main() -> None:
    print("=" * 60, flush=True)
    print("IServ -> Notion Sync — DEBUG BUILD", flush=True)
    print("=" * 60, flush=True)
    validate_config()

    try:
        raw_emails = fetch_iserv_emails()
    except Exception as exc:
        print(f"FATAL: IServ fetch failed: {exc}", flush=True)
        import traceback
        traceback.print_exc()
        sys.exit(1)

    if not raw_emails:
        print("No emails to sync — done.", flush=True)
        return

    parsed = []
    for raw in raw_emails:
        try:
            parsed.append(parse_email(raw))
        except Exception as exc:
            print(f"Parse error: {exc}", flush=True)
    print(f"\nParsed {len(parsed)} emails", flush=True)

    for i, email in enumerate(parsed[:3]):
        print(f"  Email {i}: subject='{email['subject'][:50]}' sender='{email['sender'][:50]}' date='{email['date_iso']}' uid='{email['uid']}'", flush=True)

    existing = get_existing_uids()

    new = skip = err = 0
    for email in parsed:
        if email["uid"] and email["uid"] in existing:
            skip += 1
            continue
        try:
            if create_notion_page(email):
                new += 1
            else:
                err += 1
        except Exception as exc:
            print(f"Create page failed: {exc}", flush=True)
            err += 1
        time.sleep(RATE_LIMIT_SEC)

    print(f"\nSync complete: {new} new | {skip} skipped | {err} errors", flush=True)


if __name__ == "__main__":
    main()
