#!/usr/bin/env python3
"""
IServ to Notion Sync
====================
Syncs emails from an IServ school platform to a Notion database.
Runs as a daily GitHub Actions cron job.

Author: Generated by Sol (Notion AI)
License: MIT
"""

import os
import sys
import json
import time
import logging
from datetime import datetime
from typing import Dict, List, Any, Optional

import requests
from IServAPI import IServAPI
from bs4 import BeautifulSoup

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

ISERV_USERNAME = os.environ.get("ISERV_USERNAME")
ISERV_PASSWORD = os.environ.get("ISERV_PASSWORD")
ISERV_URL = os.environ.get("ISERV_URL")  # Domain only, e.g. "adolfinum.de" — NOT "https://adolfinum.de/iserv/"
NOTION_TOKEN = os.environ.get("NOTION_TOKEN")
NOTION_DATABASE_ID = os.environ.get("NOTION_DATABASE_ID")

NOTION_API_URL = "https://api.notion.com/v1"
NOTION_VERSION = "2022-06-28"
MAX_EMAILS = 50          # Emails to fetch per run
RATE_LIMIT_SEC = 0.35   # Delay between Notion API calls

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# IServ helpers
# ---------------------------------------------------------------------------

def validate_config() -> None:
    """Exit if any required environment variable is missing."""
    required = [
        "ISERV_USERNAME", "ISERV_PASSWORD", "ISERV_URL",
        "NOTION_TOKEN", "NOTION_DATABASE_ID",
    ]
    missing = [v for v in required if not os.environ.get(v)]
    if missing:
        logger.error(f"Missing environment variables: {', '.join(missing)}")
        sys.exit(1)


def fetch_iserv_emails() -> List[Dict[str, Any]]:
    """Connect to IServ and return the latest emails from INBOX."""
    logger.info(f"Connecting to IServ at {{https://{ISERV_URL}}}/iserv/ …")

    iserv = IServAPI(
        username=ISERV_USERNAME,
        password=ISERV_PASSWORD,
        iserv_url=ISERV_URL,  # library appends /iserv/ itself
    )
    logger.info("IServ login successful")

    logger.info(f"Fetching latest {MAX_EMAILS} emails from INBOX …")
    raw = iserv.get_emails(
        path="INBOX", length=MAX_EMAILS, start=0, order="date", dir="desc"
    )

    # get_emails() returns parsed JSON from IServ's <script id="php-data"> tag.
    # The structure may be {"data": [...], ...} or a bare list.
    if isinstance(raw, dict) and "data" in raw:
        emails = raw["data"]
    elif isinstance(raw, list):
        emails = raw
    elif isinstance(raw, dict):
        # Maybe the dict itself is a single email or a wrapper without "data"
        emails = [raw]
    else:
        logger.warning(f"Unexpected response type: {type(raw)}")
        emails = []

    logger.info(f"Retrieved {len(emails)} emails from IServ")
    if emails:
        logger.debug(f"First email keys: {list(emails[0].keys()) if isinstance(emails[0], dict) else 'N/A'}")

    return emails


def _first(row: Dict[str, Any], *keys: str) -> Optional[Any]:
    """Return the first non-None value found under any of the given keys."""
    for k in keys:
        if k in row and row[k] is not None:
            return row[k]
    return None


def parse_email(raw: Dict[str, Any]) -> Dict[str, Any]:
    """Normalise a raw IServ email dict into a flat record."""
    uid = _first(raw, "uid", "UID", "id", "ID", "message_id", "messageId")
    subject = _first(raw, "subject", "Subject", "betreff", "Betreff")
    sender = _first(raw, "from", "From", "from_name", "sender", "absender")
    date_val = _first(raw, "date", "Date", "date_timestamp", "timestamp")
    seen = _first(raw, "seen", "read", "is_read", "gelesen")
    preview = _first(raw, "preview", "snippet", "excerpt", "vorschau", "text")

    # Subject
    subject = str(subject).strip() if subject else "(Kein Betreff)"

    # Sender
    sender = str(sender).strip() if sender else "Unbekannt"

    # Date — try Unix timestamp, then common string formats
    date_iso: Optional[str] = None
    if date_val is not None:
        if isinstance(date_val, (int, float)):
            date_iso = datetime.fromtimestamp(int(date_val)).isoformat()
        else:
            ds = str(date_val).strip()
            for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S", "%d.%m.%Y %H:%M:%S", "%Y-%m-%d %H:%M"):
                try:
                    date_iso = datetime.strptime(ds, fmt).isoformat()
                    break
                except ValueError:
                    continue
            if date_iso is None:
                try:
                    date_iso = datetime.fromisoformat(ds).isoformat()
                except (ValueError, TypeError):
                    logger.warning(f"Could not parse date: {ds}")
                    date_iso = datetime.now().isoformat()

    # Read status
    if isinstance(seen, bool):
        is_read = seen
    elif isinstance(seen, str):
        is_read = seen.lower() in ("true", "1", "yes", "gelesen")
    else:
        is_read = False

    # Preview
    if preview:
        preview = str(preview).strip()
        if len(preview) > 200:
            preview = preview[:200] + "…"
    else:
        preview = ""

    # UID
    uid_str = str(uid).strip() if uid is not None else None

    return {
        "uid": uid_str,
        "subject": subject,
        "sender": sender,
        "date_iso": date_iso,
        "is_read": is_read,
        "preview": preview,
    }


# ---------------------------------------------------------------------------
# Notion helpers
# ---------------------------------------------------------------------------

def notion_headers() -> Dict[str, str]:
    return {
        "Authorization": f"Bearer {NOTION_TOKEN}",
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
    }


def get_existing_uids() -> set:
    """Return the set of all IServ UIDs already stored in Notion."""
    existing = set()
    cursor = None
    has_more = True

    while has_more:
        body = {"page_size": 100}
        if cursor:
            body["start_cursor"] = cursor

        resp = requests.post(
            f"{NOTION_API_URL}/databases/{NOTION_DATABASE_ID}/query",
            headers=notion_headers(),
            json=body,
        )
        if resp.status_code != 200:
            logger.error(f"Notion query failed: {resp.status_code} — {resp.text[:300]}")
            break

        data = resp.json()
        for page in data.get("results", []):
            props = page.get("properties", {})
            uid_prop = props.get("IServ UID", {})
            rt = uid_prop.get("rich_text", [])
            if rt:
                existing.add(rt[0].get("plain_text", ""))

        has_more = data.get("has_more", False)
        cursor = data.get("next_cursor")

    logger.info(f"Found {len(existing)} existing emails in Notion")
    return existing


def create_notion_page(email: Dict[str, Any]) -> bool:
    """Create a single page in the Notion database. Returns True on success."""
    properties = {
        "Betreff": {"title": [{"text": {"content": email["subject"][:2000]}}]},
        "Absender": {"rich_text": [{"text": {"content": email["sender"][:2000]}}]},
        "Gelesen": {"checkbox": email["is_read"]},
        "Vorschau": {"rich_text": [{"text": {"content": email["preview"][:2000]}}]},
        "Ordner": {"select": {"name": "Posteingang"}},
    }

    if email["date_iso"]:
        properties["Datum"] = {"date": {"start": email["date_iso"]}}

    if email["uid"]:
        properties["IServ UID"] = {"rich_text": [{"text": {"content": email["uid"]}}]}

    resp = requests.post(
        f"{NOTION_API_URL}/pages",
        headers=notion_headers(),
        json={"parent": {"database_id": NOTION_DATABASE_ID}, "properties": properties},
    )

    if resp.status_code == 200:
        logger.info(f"  ✓ Created: {email['subject'][:60]}")
        return True
    else:
        logger.error(f"  ✗ Failed ({resp.status_code}): {resp.text[:200]}")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    logger.info("═══ IServ → Notion Sync ═══")
    validate_config()

    # 1. Fetch emails from IServ
    try:
        raw_emails = fetch_iserv_emails()
    except Exception as exc:
        logger.error(f"IServ fetch failed: {exc}")
        sys.exit(1)

    if not raw_emails:
        logger.info("No emails to sync — done.")
        return

    # 2. Parse
    parsed = []
    for raw in raw_emails:
        try:
            parsed.append(parse_email(raw))
        except Exception as exc:
            logger.error(f"Parse error for one email: {exc}")
    logger.info(f"Parsed {len(parsed)} emails")

    # 3. Dedup
    existing = get_existing_uids()

    # 4. Create new pages
    new = skip = err = 0
    for email in parsed:
        if email["uid"] and email["uid"] in existing:
            skip += 1
            continue
        try:
            if create_notion_page(email):
                new += 1
            else:
                err += 1
        except Exception as exc:
            logger.error(f"Create page failed for '{email['subject'][:40]}': {exc}")
            err += 1
        time.sleep(RATE_LIMIT_SEC)

    logger.info(f"═══ Sync complete: {new} new | {skip} skipped | {err} errors ═══")


if __name__ == "__main__":
    main()
