#!/usr/bin/env python3
"""
IServ to Notion Sync
====================
Syncs emails from an IServ school platform to a Notion database.
Runs as a daily GitHub Actions cron job.

Author: Generated by Sol (Notion AI)
License: MIT
"""

import os
import sys
import json
import time
import logging
import importlib.util
from datetime import datetime
from typing import Dict, List, Any, Optional

import requests

# ---------------------------------------------------------------------------
# IServAPI bug workaround (v1.4.0)
# ---------------------------------------------------------------------------
# IServAPI's __init__.py uses AlarmType, Recurring, and Literal as type hints
# in the create_event() method but never imports them. The line
# `from turtle import st` is clearly a mistake — should be typing imports.
# We patch the installed file before importing to avoid NameError.
_spec = importlib.util.find_spec("IServAPI")
if _spec and _spec.origin:
    with open(_spec.origin, "r") as _f:
        _content = _f.read()
    if "from turtle import st" in _content:
        _content = _content.replace(
            "from turtle import st",
            "from typing import Any, Literal",
        )
        _content = _content.replace(
            "\nclass IServAPI:",
            "\nAlarmType = Any\nRecurring = dict\n\nclass IServAPI:",
        )
        with open(_spec.origin, "w") as _f:
            _f.write(_content)
        logging.info("Patched IServAPI bug (missing AlarmType/Recurring/Literal)")

from IServAPI import IServAPI

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

ISERV_USERNAME = os.environ.get("ISERV_USERNAME")
ISERV_PASSWORD = os.environ.get("ISERV_PASSWORD")
ISERV_URL = os.environ.get("ISERV_URL")  # Domain only, e.g. "adolfinum.de"
NOTION_TOKEN = os.environ.get("NOTION_TOKEN")
NOTION_DATABASE_ID = os.environ.get("NOTION_DATABASE_ID")

NOTION_API_URL = "https://api.notion.com/v1"
NOTION_VERSION = "2022-06-28"
MAX_EMAILS = 50          # Emails to fetch per run
RATE_LIMIT_SEC = 0.35   # Delay between Notion API calls

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.DEBUG,  # DEBUG to see raw response structure
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Debug helpers
# ---------------------------------------------------------------------------

def _debug_dump_response(raw: Any, label: str = "") -> None:
    """Log the full structure of the raw IServ response for debugging."""
    logger.info(f"=== RAW RESPONSE DEBUG{' (' + label + ')' if label else ''} ===")
    logger.info(f"Type: {type(raw).__name__}")

    if isinstance(raw, dict):
        logger.info(f"Top-level keys: {list(raw.keys())}")
        for k, v in raw.items():
            if k == "data" and isinstance(v, list):
                logger.info(f"  data: list of {len(v)} items")
                if v:
                    if isinstance(v[0], dict):
                        logger.info(f"  data[0] keys: {list(v[0].keys())}")
                        for ik, iv in v[0].items():
                            val_str = str(iv)[:300] if iv is not None else "None"
                            logger.info(f"    {ik}: {val_str}")
                    else:
                        logger.info(f"  data[0] type: {type(v[0]).__name__}, value: {str(v[0])[:300]}")
            elif isinstance(v, (list, dict)):
                logger.info(f"  {k}: {type(v).__name__} (len={len(v) if isinstance(v, list) else len(v.keys())})")
            else:
                logger.info(f"  {k}: {str(v)[:300] if v is not None else 'None'}")
    elif isinstance(raw, list):
        logger.info(f"List length: {len(raw)}")
        if raw:
            if isinstance(raw[0], dict):
                logger.info(f"First item keys: {list(raw[0].keys())}")
                for k, v in raw[0].items():
                    logger.info(f"  {k}: {str(v)[:300] if v is not None else 'None'}")
            else:
                logger.info(f"First item type: {type(raw[0]).__name__}, value: {str(raw[0])[:300]}")
    else:
        logger.info(f"Value: {str(raw)[:500]}")
    logger.info("=== END RAW RESPONSE DEBUG ===")


# ---------------------------------------------------------------------------
# IServ helpers
# ---------------------------------------------------------------------------

def validate_config() -> None:
    """Exit if any required environment variable is missing."""
    required = [
        "ISERV_USERNAME", "ISERV_PASSWORD", "ISERV_URL",
        "NOTION_TOKEN", "NOTION_DATABASE_ID",
    ]
    missing = [v for v in required if not os.environ.get(v)]
    if missing:
        logger.error(f"Missing environment variables: {', '.join(missing)}")
        sys.exit(1)


def fetch_iserv_emails() -> List[Dict[str, Any]]:
    """Connect to IServ and return the latest emails from INBOX."""
    logger.info(f"Connecting to IServ at {{https://{ISERV_URL}}}/iserv/ …")

    iserv = IServAPI(
        username=ISERV_USERNAME,
        password=ISERV_PASSWORD,
        iserv_url=ISERV_URL,
    )
    logger.info("IServ login successful")

    raw = None

    # Method 1: get_email_info() — returns .json() directly from API endpoint
    logger.info(f"Trying get_email_info() (length={MAX_EMAILS}) …")
    try:
        raw = iserv.get_email_info(
            path="INBOX", length=MAX_EMAILS, start=0, order="date", dir="desc"
        )
        logger.info(f"get_email_info() succeeded, type: {type(raw).__name__}")
        _debug_dump_response(raw, "get_email_info")
    except Exception as exc:
        logger.warning(f"get_email_info() failed: {exc}")
        raw = None

    # Method 2: get_emails() — parses HTML <script id="php-data"> tag
    if not raw:
        logger.info(f"Falling back to get_emails() …")
        try:
            raw = iserv.get_emails(
                path="INBOX", length=MAX_EMAILS, start=0, order="date", dir="desc"
            )
            logger.info(f"get_emails() succeeded, type: {type(raw).__name__}")
            _debug_dump_response(raw, "get_emails")
        except Exception as exc:
            logger.error(f"get_emails() also failed: {exc}")
            return []

    # Extract email list from response
    if isinstance(raw, dict) and "data" in raw:
        emails = raw["data"]
    elif isinstance(raw, list):
        emails = raw
    elif isinstance(raw, dict):
        emails = [raw]
    else:
        logger.warning(f"Unexpected response type: {type(raw)}")
        emails = []

    logger.info(f"Retrieved {len(emails)} emails from IServ")
    return emails


def _first(row: Dict[str, Any], *keys: str) -> Optional[Any]:
    """Return the first non-None value found under any of the given keys."""
    for k in keys:
        if k in row and row[k] is not None:
            return row[k]
    return None


def _strip_html(text: Any) -> str:
    """Strip HTML tags from a string value."""
    if text is None:
        return ""
    s = str(text)
    # Quick HTML tag strip without BeautifulSoup dependency
    import re
    s = re.sub(r'<[^>]+>', '', s)
    s = s.replace('&amp;', '&').replace('&lt;', '<').replace('&gt;', '>')
    s = s.replace('&quot;', '"').replace('&#39;', "'").replace('&nbsp;', ' ')
    return s.strip()


def parse_email(raw: Dict[str, Any]) -> Dict[str, Any]:
    """Normalise a raw IServ email dict into a flat record."""
    # Log all keys of this email for debugging
    logger.debug(f"parse_email keys: {list(raw.keys()) if isinstance(raw, dict) else type(raw)}")

    # Try many possible field names, including DataTables-style numbered columns
    uid = _first(raw, "uid", "UID", "id", "ID", "message_id", "messageId",
                 "DT_RowId", "rowId", "msg", "messageId", "number")
    subject = _first(raw, "subject", "Subject", "betreff", "Betreff",
                    "title", "Title", "name", "Name")
    sender = _first(raw, "from", "From", "from_name", "sender", "absender",
                    "fromEmail", "from_email", "senderEmail", "sender_email")
    date_val = _first(raw, "date", "Date", "date_timestamp", "timestamp",
                      "time", "Time", "dateReceived", "received")
    seen = _first(raw, "seen", "read", "is_read", "gelesen", "unread",
                  "isRead", "wasRead", "flags", "flag")
    preview = _first(raw, "preview", "snippet", "excerpt", "vorschau", "text",
                     "body", "content", "previewText", "preview_text")

    # If named fields not found, try numbered DataTables columns
    if subject is None:
        subject = _first(raw, "1", "2", "0")
    if sender is None:
        sender = _first(raw, "2", "3", "1")
    if date_val is None:
        date_val = _first(raw, "3", "4", "5")

    # Strip HTML from values (IServ DataTables may include HTML markup)
    subject = _strip_html(subject) if subject else "(Kein Betreff)"
    sender = _strip_html(sender) if sender else "Unbekannt"
    preview = _strip_html(preview) if preview else ""

    if not subject:
        subject = "(Kein Betreff)"
    if not sender:
        sender = "Unbekannt"

    # Date — try Unix timestamp, then common string formats
    date_iso: Optional[str] = None
    if date_val is not None:
        if isinstance(date_val, (int, float)):
            date_iso = datetime.fromtimestamp(int(date_val)).isoformat()
        else:
            ds = _strip_html(date_val)
            for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S", "%d.%m.%Y %H:%M:%S",
                        "%Y-%m-%d %H:%M", "%d.%m.%Y", "%Y-%m-%d"):
                try:
                    date_iso = datetime.strptime(ds, fmt).isoformat()
                    break
                except ValueError:
                    continue
            if date_iso is None:
                try:
                    date_iso = datetime.fromisoformat(ds).isoformat()
                except (ValueError, TypeError):
                    logger.warning(f"Could not parse date: {ds}")
                    date_iso = datetime.now().isoformat()

    # Read status
    if isinstance(seen, bool):
        is_read = seen
    elif isinstance(seen, str):
        is_read = seen.lower() in ("true", "1", "yes", "gelesen", "read")
    elif isinstance(seen, (int, float)):
        is_read = bool(seen)
    else:
        is_read = False

    # Preview
    if preview and len(preview) > 200:
        preview = preview[:200] + "…"

    # UID
    uid_str = str(uid).strip() if uid is not None else None

    return {
        "uid": uid_str,
        "subject": subject,
        "sender": sender,
        "date_iso": date_iso,
        "is_read": is_read,
        "preview": preview,
    }


# ---------------------------------------------------------------------------
# Notion helpers
# ---------------------------------------------------------------------------

def notion_headers() -> Dict[str, str]:
    return {
        "Authorization": f"Bearer {NOTION_TOKEN}",
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
    }


def get_existing_uids() -> set:
    """Return the set of all IServ UIDs already stored in Notion."""
    existing = set()
    cursor = None
    has_more = True

    while has_more:
        body = {"page_size": 100}
        if cursor:
            body["start_cursor"] = cursor

        resp = requests.post(
            f"{NOTION_API_URL}/databases/{NOTION_DATABASE_ID}/query",
            headers=notion_headers(),
            json=body,
        )
        if resp.status_code != 200:
            logger.error(f"Notion query failed: {resp.status_code} — {resp.text[:300]}")
            break

        data = resp.json()
        for page in data.get("results", []):
            props = page.get("properties", {})
            uid_prop = props.get("IServ UID", {})
            rt = uid_prop.get("rich_text", [])
            if rt:
                existing.add(rt[0].get("plain_text", ""))

        has_more = data.get("has_more", False)
        cursor = data.get("next_cursor")

    logger.info(f"Found {len(existing)} existing emails in Notion")
    return existing


def create_notion_page(email: Dict[str, Any]) -> bool:
    """Create a single page in the Notion database. Returns True on success."""
    properties = {
        "Betreff": {"title": [{"text": {"content": email["subject"][:2000]}}]},
        "Absender": {"rich_text": [{"text": {"content": email["sender"][:2000]}}]},
        "Gelesen": {"checkbox": email["is_read"]},
        "Vorschau": {"rich_text": [{"text": {"content": email["preview"][:2000]}}]},
        "Ordner": {"select": {"name": "Posteingang"}},
    }

    if email["date_iso"]:
        properties["Datum"] = {"date": {"start": email["date_iso"]}}

    if email["uid"]:
        properties["IServ UID"] = {"rich_text": [{"text": {"content": email["uid"]}}]}

    resp = requests.post(
        f"{NOTION_API_URL}/pages",
        headers=notion_headers(),
        json={"parent": {"database_id": NOTION_DATABASE_ID}, "properties": properties},
    )

    if resp.status_code == 200:
        logger.info(f"  ✓ Created: {email['subject'][:60]}")
        return True
    else:
        logger.error(f"  ✗ Failed ({resp.status_code}): {resp.text[:200]}")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    logger.info("═══ IServ → Notion Sync ═══")
    validate_config()

    # 1. Fetch emails from IServ
    try:
        raw_emails = fetch_iserv_emails()
    except Exception as exc:
        logger.error(f"IServ fetch failed: {exc}")
        sys.exit(1)

    if not raw_emails:
        logger.info("No emails to sync — done.")
        return

    # 2. Parse
    parsed = []
    for raw in raw_emails:
        try:
            parsed.append(parse_email(raw))
        except Exception as exc:
            logger.error(f"Parse error for one email: {exc}")
    logger.info(f"Parsed {len(parsed)} emails")

    # 3. Dedup
    existing = get_existing_uids()

    # 4. Create new pages
    new = skip = err = 0
    for email in parsed:
        if email["uid"] and email["uid"] in existing:
            skip += 1
            continue
        try:
            if create_notion_page(email):
                new += 1
            else:
                err += 1
        except Exception as exc:
            logger.error(f"Create page failed for '{email['subject'][:40]}': {exc}")
            err += 1
        time.sleep(RATE_LIMIT_SEC)

    logger.info(f"═══ Sync complete: {new} new | {skip} skipped | {err} errors ═══")


if __name__ == "__main__":
    main()
